// <auto-generated />
using Microsoft.AspNetCore.Hosting;

[assembly: HostingStartup(typeof(Lekarna.Web.Areas.Identity.IdentityHostingStartup))]

namespace Lekarna.Web.Areas.Identity
{
    public class IdentityHostingStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder builder)
        {
            builder.ConfigureServices((context, services) => {
            });
        }
    }
}